MASSHUU12/godot-yat

README.md, addons/yat/YAT.cs, addons/yat/options/YatOptions.cs, addons/yat/options/YatOptions.tres
=> YAT enable file

addons/yat/src/commands/builtin/Echo.cs, addons/yat/src/commands/builtin/List.cs, addons/yat/src/commands/builtin/Man.cs, addons/yat/src/commands/builtin/Options.cs, addons/yat/src/commands/builtin/Quit.cs, addons/yat/src/commands/builtin/Restart.cs, addons/yat/src/commands/builtin/Set.cs, addons/yat/src/commands/builtin/View.cs, addons/yat/src/commands/builtin/Whereami.cs, addons/yat/src/helpers/LogHelper.cs, addons/yat/src/options/OptionsManager.cs, addons/yat/src/overlay/components/terminal/Terminal.cs, example/SetCube.cs
=> Fix text formatting

CHANGELOG.md, addons/yat/plugin.cfg
=> v1.4.0-beta

CHANGELOG.md, addons/yat/src/scenes/overlay/components/terminal/Terminal.cs
=> Fix terminal centering issue

CHANGELOG.md, addons/yat/src/attributes/ArgumentAttribute.cs, addons/yat/src/attributes/OptionAttribute.cs, addons/yat/src/helpers/AttributeHelper.cs, addons/yat/src/helpers/CommandHelper.cs, addons/yat/src/helpers/LruCache.cs, addons/yat/src/helpers/NumericHelper.cs, addons/yat/src/helpers/StorageHelper.cs, addons/yat/src/interfaces/ICommand.cs, addons/yat/src/interfaces/IExtension.cs, addons/yat/src/scenes/overlay/components/terminal/components/autocompletion/Autocompletion.cs, godot-yat.csproj
=> Prevent potentially null values

CHANGELOG.md, addons/yat/docs/CREATING_COMMANDS.md, addons/yat/src/YAT.cs, addons/yat/src/scenes/terminal/Terminal.cs, addons/yat/src/scenes/terminal/components/input/Input.cs, example/player/Player.cs
=> Input focus fix

CHANGELOG.md, addons/yat/src/interfaces/ICommand.cs
=> Fix arguments & options manual

CHANGELOG.md, addons/yat/docs/BUILTIN_COMMANDS.md, addons/yat/src/YAT.cs, addons/yat/src/commands/builtin/Cs.cs
=> Cs command

CHANGELOG.md, addons/yat/docs/CREATING_COMMANDS.md, addons/yat/src/commands/builtin/Man.cs, addons/yat/src/helpers/Reflection.cs, addons/yat/src/interfaces/ICommand.cs
=> Automatic manuals for signals

CHANGELOG.md, addons/yat/docs/CUSTOM_WINDOWS.md, addons/yat/src/scenes/monitor/Monitor.cs, addons/yat/src/scenes/settings_window/SettingsWindow.cs, addons/yat/src/scenes/terminal/Terminal.cs, addons/yat/src/scenes/yat_window/YatWindow.cs
=> Fix YatWindow scaling

CHANGELOG.md, addons/yat/src/interfaces/ICommand.cs
=> 116 options header is displayed in man when command does not have any options

CHANGELOG.md, addons/yat/src/commands/builtin/Cn.cs, addons/yat/src/commands/builtin/Ls.cs, addons/yat/src/commands/builtin/Whereami.cs, addons/yat/src/scenes/terminal/Terminal.cs, addons/yat/src/scenes/terminal/components/selected_node/SelectedNode.cs
=> Log errors in cn command

CHANGELOG.md, README.md, addons/yat/README.md, addons/yat/src/helpers/TextHelper.cs, addons/yat/src/scenes/terminal/Terminal.cs, addons/yat/src/scenes/terminal/Terminal.tscn, addons/yat/src/scenes/terminal/components/autocompletion/Autocompletion.cs, addons/yat/src/scenes/terminal/theme/yat_terminal_label_theme.tres, addons/yat/src/scenes/terminal/theme/yat_terminal_line_edit_theme.tres
=> Limit width of selected node label

CHANGELOG.md, addons/yat/docs/USAGE.md, addons/yat/src/helpers/Keybindings.cs, addons/yat/src/scenes/base_terminal/components/autocompletion/Autocompletion.cs
=> Action to go back in autocompletion

CHANGELOG.md, addons/yat/docs/USAGE.md, addons/yat/src/YAT.cs, addons/yat/src/helpers/Keybindings.cs, addons/yat/src/options/OptionsManager.cs, addons/yat/src/scenes/base_terminal/BaseTerminal.cs, addons/yat/src/scenes/base_terminal/components/autocompletion/Autocompletion.cs, addons/yat/src/scenes/context_menu/ContextMenu.cs, addons/yat/src/scenes/game_terminal/GameTerminal.cs, example/game/Game.cs, example/player/Player.cs
=> Handle keybindings better

CHANGELOG.md, addons/yat/src/commands/builtin/Cn.cs, addons/yat/src/helpers/Text.cs, addons/yat/src/helpers/World.cs
=> Search node tree using `cn` command

CHANGELOG.md, addons/yat/docs/BUILTIN_COMMANDS.md, addons/yat/docs/TERMINAL.md, addons/yat/src/YAT.cs, addons/yat/src/commands/builtin/Reset.cs, addons/yat/src/scenes/base_terminal/BaseTerminal.cs, addons/yat/src/scenes/game_terminal/GameTerminal.cs, addons/yat/src/scenes/monitor/Monitor.cs, addons/yat/src/scenes/yat_window/YatWindow.cs
=> More options for yat window

CHANGELOG.md, addons/yat/docs/BUILTIN_COMMANDS.md, addons/yat/src/YAT.cs, addons/yat/src/commands/builtin/Sys.cs, addons/yat/src/helpers/OS.cs, addons/yat/src/scenes/base_terminal/BaseTerminal.cs, addons/yat/src/scenes/monitor/components/memory_info/MemoryInfo.cs
=> Sys command

CHANGELOG.md, addons/yat/src/helpers/AttributeHelper.cs, addons/yat/src/interfaces/ICommand.cs
=> 156 man command should display information if command is threaded

CHANGELOG.md, README.md, addons/yat/README.md, addons/yat/docs/BUILTIN_COMMANDS.md, addons/yat/src/YAT.cs, addons/yat/src/commands/builtin/Timescale.cs
=> Timescale command

CHANGELOG.md, addons/yat/docs/BUILTIN_COMMANDS.md, addons/yat/src/YAT.cs, addons/yat/src/commands/builtin/ToggleAudio.cs, example/assets/ATTRIBUTION.txt, example/assets/glaciære - two months of moments - 01 Into the Maelstrom.mp3.import, example/game/Game.tscn
=> Toggle audio command

CHANGELOG.md, addons/yat/src/YAT.cs, addons/yat/src/YAT.tscn, addons/yat/src/commands/builtin/Cowsay.cs, addons/yat/src/commands/builtin/History.cs, addons/yat/src/commands/builtin/Ping.cs, addons/yat/src/commands/builtin/Quit.cs, addons/yat/src/commands/builtin/Stats.cs, addons/yat/src/commands/builtin/View.cs, addons/yat/src/commands/builtin/Watch.cs, addons/yat/src/commands/builtin/Wenv.cs, addons/yat/src/scenes/base_terminal/BaseTerminal.cs, addons/yat/src/scenes/base_terminal/components/input/Input.cs, addons/yat/src/scenes/base_terminal/components/terminal_context/quic_commands_context/QuickCommandsContext.cs, addons/yat/src/scenes/command_manager/CommandManager.cs, addons/yat/src/scenes/game_terminal/GameTerminal.cs, addons/yat/src/scenes/terminal_manager/TerminalManager.cs, addons/yat/src/scenes/terminal_manager/TerminalManager.tscn, addons/yat/src/types/CommandData.cs, example/SetCube.cs, example/player/Player.cs
=> Partiall terminal independence of YAT

CHANGELOG.md, addons/yat/docs/CREATING_COMMANDS.md, addons/yat/src/YAT.cs, addons/yat/src/commands/builtin/List.cs, addons/yat/src/commands/builtin/Man.cs, addons/yat/src/commands/builtin/Watch.cs, addons/yat/src/scenes/base_terminal/components/autocompletion/Autocompletion.cs, addons/yat/src/scenes/base_terminal/components/input_info/components/command_info/CommandInfo.cs, addons/yat/src/scenes/command_manager/CommandManager.cs, example/game/Game.cs
=> Move adding commands to the CommandManager

CHANGELOG.md, addons/yat/docs/classes/YatWindow.md, addons/yat/src/scenes/game_terminal/GameTerminal.tscn, addons/yat/src/scenes/yat_window/YatWindow.cs, addons/yat/src/scenes/yat_window/YatWindow.tscn
=> Implement AllowToGoOffScreen variable

CHANGELOG.md, addons/yat/docs/classes/Extensible.md, addons/yat/docs/classes/Reflection.md, addons/yat/src/commands/Extensible.cs, addons/yat/src/commands/builtin/Set.cs, addons/yat/src/enums/CommandResult.cs, addons/yat/src/helpers/Reflection.cs, addons/yat/src/interfaces/IExtension.cs, addons/yat/src/scenes/game_terminal/GameTerminal.tscn, example/SetCube.cs, example/game/Game.cs, script_templates/Node/ExtensibleCommand.cs, test/commands/TestExtensible.cs
=> Rework command extension system

CHANGELOG.md, addons/yat/docs/classes/Scene.md, addons/yat/src/classes/Parser.cs, addons/yat/src/commands/builtin/Ls.cs, addons/yat/src/enums/MethodValidationResult.cs, addons/yat/src/helpers/Messages.cs, addons/yat/src/helpers/Scene.cs, addons/yat/src/scenes/base_terminal/components/selected_node/SelectedNode.cs, addons/yat/src/types/NodeMethodInfo.cs
=> Method chaining

CHANGELOG.md, addons/yat/src/commands/builtin/Stats.cs, addons/yat/src/scenes/monitor/components/memory_info/MemoryInfo.tscn, addons/yat/src/scenes/monitor/theme/yat_monitor_theme.tres
=> Update monitor & stats command

CHANGELOG.md, addons/yat/src/attributes/CommandAttribute.cs, addons/yat/src/attributes/DescriptionAttribute.cs, addons/yat/src/commands/Echo.cs, addons/yat/src/commands/List.cs, addons/yat/src/interfaces/ICommand.cs
=> Description attribute

CHANGELOG.md, addons/yat/docs/CREATING_COMMANDS.md, addons/yat/src/attributes/UsageAttribute.cs, addons/yat/src/commands/Echo.cs, addons/yat/src/interfaces/ICommand.cs
=> Usage attribute

CHANGELOG.md, addons/yat/docs/BUILTIN_COMMANDS.md, addons/yat/src/commands/Crash.cs, addons/yat/src/scenes/registered_commands/RegisteredCommands.cs
=> Add `crash` command

CHANGELOG.md, addons/yat/docs/BUILTIN_COMMANDS.md, addons/yat/src/commands/Forcegc.cs, addons/yat/src/scenes/registered_commands/RegisteredCommands.cs
=> Add `forcegc` command

CHANGELOG.md, README.md, addons/yat/README.md, addons/yat/docs/BUILTIN_COMMANDS.md, addons/yat/src/commands/Tfs.cs, addons/yat/src/scenes/registered_commands/RegisteredCommands.cs
=> Add `tfs` command

CHANGELOG.md, addons/yat/docs/USAGE.md, addons/yat/docs/classes/BaseTerminal.md, addons/yat/docs/classes/FullWindowDisplay.md, addons/yat/docs/classes/Input.md, addons/yat/src/commands/Man.cs, addons/yat/src/helpers/Keybindings.cs, addons/yat/src/scenes/base_terminal/BaseTerminal.cs, addons/yat/src/scenes/base_terminal/BaseTerminal.tscn, addons/yat/src/scenes/base_terminal/components/full_window_display/FullWindowDisplay.cs, addons/yat/src/scenes/base_terminal/components/full_window_display/FullWindowDisplay.tscn, addons/yat/src/scenes/base_terminal/components/input/Input.cs, addons/yat/src/scenes/game_terminal/components/terminal_switcher/TerminalSwitcher.cs, addons/yat/src/scenes/game_terminal/components/terminal_switcher/TerminalSwitcher.tscn
=> Add full window display

.gitattributes, CHANGELOG.md
=> Fix exported ZIP

addons/yat/src/commands/List.cs
=> feat: Better help information output

CHANGELOG.md, addons/yat/docs/YAT_ENABLE.md, addons/yat/src/YAT.cs, addons/yat/src/YAT.tscn, addons/yat/src/enums/EYatEnableLocation.cs, addons/yat/src/resources/preferences/YatPreferences.cs, addons/yat/src/scenes/terminal_manager/TerminalManager.cs, addons/yat/src/scenes/yat_enable/YatEnable.cs, addons/yat/src/scenes/yat_enable/YatEnable.tscn, scripts/run_yat_w_flag.ps1
=> Rework Yat Enable

CHANGELOG.md, addons/yat/src/commands/Ds.cs, addons/yat/src/scenes/debug_screen/DebugScreen.cs
=> Control DebugScreen's interval via `ds` command

CHANGELOG.md, addons/yat/docs/QUICK_COMMANDS.md, addons/yat/src/scenes/base_terminal/components/input/Input.cs
=> Allow calling Quick Commands w/o GUI

.vscode/tasks.json, CHANGELOG.md, addons/yat/src/classes/managers/command_manager/CommandManager.cs, addons/yat/src/scenes/registered_commands/RegisteredCommands.cs
=> Fix leaked objects

CHANGELOG.md, addons/confirma/docs/TESTING.md, addons/confirma/plugin.cfg, addons/confirma/src/attributes/IgnoreAttribute.cs, addons/confirma/src/classes/TestCase.cs, addons/confirma/src/classes/TestDiscovery.cs, addons/confirma/src/classes/TestExecutor.cs, addons/confirma/src/classes/TestingMethod.cs, addons/confirma/src/enums/EIgnoreMode.cs, addons/confirma/src/extensions/ConfirmArrayExtensions.cs, addons/confirma/src/extensions/ConfirmAttributeExtensions.cs, addons/confirma/src/extensions/ConfirmBooleanExtensions.cs, addons/confirma/src/extensions/ConfirmEqualExtensions.cs, addons/confirma/src/extensions/ConfirmExceptionExtensions.cs, addons/confirma/src/extensions/ConfirmFileExtensions.cs, addons/confirma/src/extensions/ConfirmIEnumerableExtensions.cs, addons/confirma/src/extensions/ConfirmNullExtensions.cs, addons/confirma/src/extensions/ConfirmTypeExtensions.cs, addons/confirma/src/extensions/ConfirmVectorExtensions.cs, addons/confirma/src/helpers/ArrayHelper.cs, addons/confirma/src/helpers/Reflection.cs, addons/confirma/src/types/TestResult.cs, addons/yat/src/classes/Parser.cs, test/classes/ParserTest.cs
=> Fix bugs detected by tests

.vscode/settings.json, CHANGELOG.md, addons/yat/Plugin.cs, addons/yat/docs/BUILTIN_COMMANDS.md, addons/yat/src/classes/SemanticVersion.cs, addons/yat/src/classes/Updater.cs, addons/yat/src/commands/CheckUpdate.cs, addons/yat/src/commands/Version.cs, addons/yat/src/helpers/Release.cs, addons/yat/src/scenes/registered_commands/RegisteredCommands.cs, addons/yat/src/types/ReleaseTagInfo.cs, test/classes/SemanticVersionTest.cs
=> Create a notification when new release is available

CHANGELOG.md, addons/yat/docs/BUILTIN_COMMANDS.md, addons/yat/src/commands/Locale.cs, addons/yat/src/scenes/registered_commands/RegisteredCommands.cs
=> Add 'locale' command

CHANGELOG.md, addons/yat/src/commands/Ls.cs, addons/yat/src/helpers/Networking.cs, addons/yat/src/helpers/Numeric.cs, addons/yat/src/helpers/Scene.cs, addons/yat/src/helpers/Text.cs, test/helpers/NetworkingTest.cs, test/helpers/NetworkingTest.cs.uid, test/helpers/NumericTest.cs, test/helpers/ReflectionTest.cs, test/helpers/SceneTest.cs, test/helpers/TextTest.cs
=> test: test helpers

CHANGELOG.md, addons/yat/src/classes/clipboard/Clipboard.cs, addons/yat/src/helpers/OS.cs
=> chore: remove OS.EOperatingSystem & OS.Platform
